# Generated by Django 3.2.21 on 2023-11-14 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_playtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone',
        ),
    ]
